### ISSUE TITLE
deployment setup broken for Javascript files

### ISSUE THREAD

**Issue by ashleygwilliams** [WebAssemblySummit/webassembly-summit.org#22] opened 2019-12-03 14:02 UTC
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwebassembly-summit.org%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

**Comment by surma** [comment] 2019-12-03 14:07
Sadly we have no control of caching headers with GitHub pages :(

**Comment by ashleygwilliams** [comment] 2019-12-03 14:10
oh bleh. if we wanted to deploy to a cloudflare worker i could get us that hosting for free. doesn't actually matter matter, but lemme know. we can keep the github action deploy, plus we gain cache header access.

**Comment by ttraenkler** [comment] 2020-01-03 12:45
Regarding the browser console errors (the .js 404s), the issue seems to be addressed here: 
https://github.com/zeit/next.js/wiki/Deploying-a-Next.js-app-into-GitHub-Pages . One thing I noticed is that on mobile occasionally the SVG did not appear on first load for me. On page reload it always came back. I am not sure what the issue is, but it might be related to the 404s described in the link above.

The SVG logo caching times could be improved for people at the conference without WiFi access and an expensive tiny roaming data plan, so I think it's kinda important to address this until then. For that and offline access we should have a look at enabling service workers for next.js as mentioned earlier.

**Comment by ttraenkler** [comment] 2020-01-03 12:45
I'll unassign me from this ticket until I resume work on this, so anybody who wants to contribute can chime in.

**Comment by torch2424** [comment] 2020-01-07 07:07
Going to look into this, per @ttraenkler suggestion :smile:

**Comment by ttraenkler** [comment] 2020-01-08 11:09
I think this is related to the deployment setup. Actually investigating the issue why the onclick handler of the burger menu is not working when deployed, I realized the 404s may actually mean there is no Javascript served at all and the page falls back to static HTML - that's why no Javascript is actually working at all probably.

Here are some links related to the setup:
- https://github.com/thierryc/Next-gh-page-example
- https://github.com/zeit/next.js/wiki/Deploying-a-Next.js-app-into-GitHub-Pages#alter-link-urls

I am having a look at this as well, as now this has become a critical issue, but feel free to join in when you have some time.

**Comment by ttraenkler** [comment] 2020-01-08 11:11
I assume what happens is that we moved the github page from a user/orga page to a project page and we need to setup the domain as is described here: https://github.com/thierryc/Next-gh-page-example with a `next.config.js` and `env-config.js` as seen in this repo.

**Comment by ttraenkler** [comment] 2020-01-08 11:46
I have opened a PR with a potential fix for the broken .js assets #47 - it also contains changes to the <a> tags, but these are probably irrelevant - the important changes are in the env-config.js and next.config.js setting up the Github project repository. I can't test this locally so we would have to merge and deploy this fix and see if it fixes the issue.

**Comment by ttraenkler** [comment] 2020-01-08 15:41
@ashleygwilliams Thanks for the review. I merged the PR and it did not fix the issue, but I think we're close. I will read some more and create another PR later.

**Comment by ttraenkler** [comment] 2020-01-09 00:22
Thanks @torch2424 for the review. I merged/deployed the PR and the .js errors are gone (see new report in #52). I will address the new lighthouse audit report after this in #52.

**Closed by ttraenkler** 2020-01-09 00:22 UTC
Labels: PR welcome, bug
